import PageWrapper from "src/components/PageWrapper";
import { useScrollTop } from "src/hooks";
import "src/pages/faq.css";

const FAQ = () => {
  useScrollTop();
  return (
    <PageWrapper
      title="Frequently Asked Questions"
      documentTitle="FAQ | Adamovies"
    >
      {faqs.map(({ question, answer }) => (
        <div className="QA-container u-auto">
          <h1 className="QA-text">Q: {question}</h1>
          <hr className="line-QA" />
          <h1 className="QA-text">A: {answer}</h1>
        </div>
      ))}
    </PageWrapper>
  );
};

const faqs = [
  {
    question: "What is Adamovies?",
    answer:
      "Adamovies is a site where myself and other admins review movies and TV shows so all the users can read about them. You can check the About page for more information!",
  },
  {
    question: "Do I need an account to use Adamovies?",
    answer:
      "No! You don't have to sign in to use Adamovies, however, you won't be able to comment on or like reviews unless you do!",
  },
  {
    question: "How do I change my username?",
    answer:
      "After signing in, you can click on your name in the top right corner, which will take you to your profile page, where you can change your username, and other bio information.",
  },
  {
    question: "How can I change my email preferences?",
    answer:
      "Simply go to your profile page, click on the edit button, and then check/uncheck the box accordingly!",
  },
  {
    question:
      "After I sign in, will other users be able to see my first and last name or other private information?",
    answer:
      "The only information other users can see is your username, profile picture, your favorite show, your favorite movie, your currently watching, and your bio. Your username is randomly generated by default, but you can change it as you wish.",
  },
  {
    question: "How can I @ someone?",
    answer:
      "In the comments section, simply type in @username and a notification will be sent to that user. For example, you can type @BulkyEndymion38 to get my attention. Note: capitalization doesn't matter when using @.",
  },
  {
    question: "What does the percentage under reviews mean?",
    answer:
      "The percentage represents the score out of 100% that the admin reviewer gave to the film or show. The higher percentage, the better the admin liked it! Users can use the like feature to show their support for films or shows.",
  },
  {
    question: "How do you score reviews?",
    answer:
      "I can't speak for other admins, but this is how I score films: first, I usually have a good estimate of where the film will fall (i.e. in the 70s). Second, I'll compare the film with other films similar in content and score, and position the new film correctly.",
  },
  {
    question: "How do I post a review?",
    answer:
      "Adamovies uses an admin system, so only hand-picked users are able to post reviews. If you gain my trust through comments, I just might make you a site admin though! Feel free to @ me in the comments to ask to be an admin!",
  },
  {
    question: "What are the announcements for?",
    answer:
      "Announcements are posted by admin when we add a review we think people will want to see; it's a way of giving attention to specific reviews.",
  },
  {
    question: "Is Adamovies fun?",
    answer:
      "I think it is! I tried to design this site as a fun place for reading and talking about movies and shows!",
  },
] as const;

export default FAQ;
